# Generated by Django 5.2 on 2025-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('kategori', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('headphone', 'Headphone'), ('speaker', 'Speaker'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('gaming', 'Gaming')], max_length=20, verbose_name='Kategori')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga (Rp)')),
                ('stok', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('tersedia', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
